### ISSUE TITLE
reason: 'Could not load NIB in bundle: 'NSBundle </Users/Name/Library/Application Support/iPhone Simulator/7.1/Applications/01DEDE3A-893D-4498-8B29-A35E7BBA3C1E/ICGTransitionAnimationDemo.app> (loaded)' with name 'ICGThirdViewController''

### ISSUE THREAD

**Issue by SSA111** [itsmeichigo/ICGTransitionAnimation#2]
I get the following error when I run the demo: 

reason: 'Could not load NIB in bundle: 'NSBundle </Users/Name/Library/Application Support/iPhone Simulator/7.1/Applications/01DEDE3A-893D-4498-8B29-A35E7BBA3C1E/ICGTransitionAnimationDemo.app> (loaded)' with name 'ICGThirdViewController''

**Comment by itsmeichigo** [comment]
Hi, this has been fixed. Please download the project again.
Thanks for reporting.
