### ISSUE TITLE
How to use in storyboards?

### ISSUE THREAD

**Issue by ortizroberto** [itsmeichigo/ICGTransitionAnimation#3]
I'm loving this transitions! could you explain how to use with storyboards?

**Comment by itsmeichigo** [comment]
When you use storyboard, make sure your navigation controller's custom class is `ICGNavigationController`, just so you can set its animation controller via any of its view controller. For example, you can add this inside `viewDidLoad` method of your root view controller:

``` Objective-C
    ICGNavigationController *fancyNavigationController = (ICGNavigationController *)self.navigationController;
    ICGLayerAnimation *layerAnimation = [[ICGLayerAnimation alloc] initWithType:ICGLayerAnimationCover];
    fancyNavigationController.animationController = layerAnimation;
```

If you have any difficulty using this, please let me know. Thanks.

**Comment by ortizroberto** [comment]
I did what you wrote and it worked perfectly. Thank you so much!
