### ISSUE TITLE
Animation does not work first time - Storyboard

### ISSUE THREAD

**Issue by parvezsyed** [itsmeichigo/ICGTransitionAnimation#5]
I am using storyboards. My Navigation controller is connected to a tabview controller.

When I initialize any of my view controllers connected to the navigation controller, the animation is stuck to whatever previous animation (if another view uses slide from left, it is stuck on that) for the very first time. But, it works perfectly when the view gets dismissed.

Please check

**Comment by itsmeichigo** [comment]
Can you please confirm which version you are using?

**Comment by parvezsyed** [comment]
1.01 confirmed

pod 'ICGTransitionAnimation', '~> 1.01'

On Tue, Jul 15, 2014 at 7:08 PM, Huong Do notifications@github.com wrote:

> Can you please confirm which version you are using?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/itsmeichigo/ICGTransitionAnimation/issues/5#issuecomment-49115881
> .

## 

Thanks
Parvez Syed Mohamed

**Comment by itsmeichigo** [comment]
I have pushed my storyboard demo. I'm still investigating the bug you raised, so if possible please use my demo and report back with the steps you do to cause that bug.

Thanks.

**Comment by parvezsyed** [comment]
Thanks Huong, I will try asap

On Wed, Jul 16, 2014 at 11:54 PM, Huong Do notifications@github.com wrote:

> I have pushed my storyboard demo. I'm still investigate the bug you
> raised, so if possible please use my demo and report back with the steps
> you do to cause that bug.
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/itsmeichigo/ICGTransitionAnimation/issues/5#issuecomment-49265108
> .

## 

Thanks
Parvez Syed Mohamed

**Comment by parvezsyed** [comment]
Amazing, works great with storyboards.

One minor bug, Flip remains same for left or right.

One more question, How do I animate tab bar transitions? I would love to
flip/slide through views in the tab bar.

On Thu, Jul 17, 2014 at 12:25 AM, Parvez Syed parvezsyed@gmail.com wrote:

> Thanks Huong, I will try asap
> 
> On Wed, Jul 16, 2014 at 11:54 PM, Huong Do notifications@github.com
> wrote:
> 
> > I have pushed my storyboard demo. I'm still investigate the bug you
> > raised, so if possible please use my demo and report back with the steps
> > you do to cause that bug.
> > 
> > Thanks.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/itsmeichigo/ICGTransitionAnimation/issues/5#issuecomment-49265108
> > .
> 
> ## 
> 
> Thanks
> Parvez Syed Mohamed

## 

Thanks
Parvez Syed Mohamed

**Comment by itsmeichigo** [comment]
I'm pretty sure the direction issue is specific to that one animation you're using. Please tell me which one you're using so I can fix it asap.

As for the tab bar, I think you probably want to add a "screenshot" of the tab bar as a subview of your main view and hide the real bar between transitions. This is just my idea, but if you can't make it yourself you'll want to create a separate issue for that.

Thanks.
