### ISSUE TITLE
Navigationbar becomes dark

### ISSUE THREAD

**Issue by soufianeEssabbane** [itsmeichigo/ICGTransitionAnimation#6]
Hi, thank you for this awesome transition, i'm trying to implement this in my project and under ios 7.0 the navigationbar gets darker ... 
any idea ?
thanks

**Comment by itsmeichigo** [comment]
Can you explain further the issue you're encountering? A screenshot would be really helpful.

**Comment by soufianeEssabbane** [comment]
Thanks for the reply

**Comment by soufianeEssabbane** [comment]
![capture decran 2014-07-17 a 04 51 26](https://cloud.githubusercontent.com/assets/1910912/3608883/64448efa-0d6c-11e4-85f3-26c0b0d3ede7.png)

**Comment by itsmeichigo** [comment]
This is probably because you pushed your view before the previous view has completed loading. Please make sure you've done everything right in your code.

**Comment by soufianeEssabbane** [comment]
hi, what do you mean by "before completed loading". I push a view and in
this view once I click on a button I represent another view moadaly... Once
I click to show the modal view the push views becomes as u've seen (Push
and modal are using CGtransition)

Thanks

**Comment by itsmeichigo** [comment]
I highly recommend you put some breakpoints and add logs to determine the root cause of the issue. Once you find out how the issue has anything to do with the library, please let me know.

Thanks.
